Repository Broccoli-and-Wings/chat-app, pull requests merged in 2018-09, with the labels that each got.

#2 Feat/node server
  .gitignore
  package-lock.json
  package.json
  server/server.js
  src/assets/images/logo.svg
  src/components/App.css
  src/components/App.js
  src/components/App.jsx
  src/components/MainRouter.jsx
  src/components/core/Home.jsx
  src/components/core/Menu.jsx
  src/components/user/Signup.jsx
  src/index.css
  src/index.js
Labels: enhancement

#1 Barebones UI. Added react-router for navigation.
  config/config.js
  src/components/App.jsx
  src/components/MainRouter.jsx
  src/components/core/Home.jsx
  src/components/core/Menu.jsx
  src/components/user/Signup.jsx
Labels: work-in-progress

#8 Feat/cra eject
  .github/PULL_REQUEST_TEMPLATE.md
  .nvmrc
  README.md
  config/env.js
  config/jest/cssTransform.js
  config/jest/fileTransform.js
  config/paths.js
  config/polyfills.js
  config/webpack.config.dev.js
  config/webpack.config.prod.js
  config/webpackDevServer.config.js
  package-lock.json
  package.json
  scripts/build.js
  scripts/start.js
  scripts/test.js
  server/server.js
  src/assets/styles/_normalize.scss
  src/assets/styles/helpers.scss
  src/components/core/Menu.jsx
  src/components/core/Menu.scss
  src/index.js
Labels: Ready for review

#10 elaborated on proptypes
  src/components/core/Menu.js
Labels: Ready for review

#11 Added precommit/prepush hooks
  .gitignore
  .prettierrc
  package-lock.json
  package.json
  server/server.js
  src/components/App.js
  src/components/MainRouter.js
  src/components/core/Home.js
  src/components/core/Menu.js
  src/components/user/Signup.js
  src/index.js
Labels: Ready for review
